# Generated by Django 4.2 on 2023-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('protagonists', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('coming-up', 'Coming up'), ('starting', 'Starting'), ('running', 'Running'), ('finished', 'Finished')], max_length=20)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
    ]
